[project]
name = "Classroom-Attendance-System"
version = "0.1.0"
description = "a classroom attendance management system for colleges and universities constructed"
authors = [
    {name = "BalconyJH", email = "balconyjh@gmail.com"},
]
dependencies = [
    "loguru>=0.7.2",
    "opencv-python>=4.8.1.78",
    "pydantic[dotenv]>=2.5.2",
    "pydantic-settings>=2.1.0",
    "dlib>=19.24.2",
    "Django>=4.2.9",
]
requires-python = ">=3.9"
readme = "README.md"
license = {text = "GPL-3.0 license"}

[tool.isort]
profile = "black"
line_length = 120
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
extra_standard_library = ["typing_extensions"]

[tool.ruff]
select = ["E", "W", "F", "UP", "C", "T", "PYI", "PT", "Q"]
ignore = ["E402", "C901", "UP037", "T201", "F403"]
line-length = 120

[tool.ruff.flake8-pytest-style]
fixture-parentheses = false
mark-parentheses = false

[tool.pyright]
pythonVersion = "3.8"
pythonPlatform = "All"
executionEnvironments = [
    { root = "./tests", extraPaths = [
        "./",
    ] },
    { root = "./" },
]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "mysite.settings"

typeCheckingMode = "basic"
reportShadowedImports = false
disableBytesTypePromotions = true

[tool.pytest.ini_options]
asyncio_mode = "auto"