"""initial migration

Revision ID: 00fdbe2e4fec
Revises: 
Create Date: 2024-02-15 01:42:28.234091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00fdbe2e4fec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("choose_course")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=mysql.VARCHAR(length=80), nullable=True)
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=320), nullable=True)

    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.alter_column("s_id", existing_type=mysql.VARCHAR(length=13), nullable=True)
        batch_op.alter_column("c_id", existing_type=mysql.VARCHAR(length=100), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=mysql.VARCHAR(length=80), nullable=True)
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=320), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=320), nullable=False)
        batch_op.alter_column("username", existing_type=mysql.VARCHAR(length=80), nullable=False)

    with op.batch_alter_table("attendance", schema=None) as batch_op:
        batch_op.alter_column("c_id", existing_type=mysql.VARCHAR(length=100), nullable=False)
        batch_op.alter_column("s_id", existing_type=mysql.VARCHAR(length=13), nullable=False)

    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.alter_column("email", existing_type=mysql.VARCHAR(length=320), nullable=False)
        batch_op.alter_column("username", existing_type=mysql.VARCHAR(length=80), nullable=False)

    op.create_table(
        "choose_course",
        sa.Column("c_id", mysql.VARCHAR(length=6), nullable=False),
        sa.Column("t_id", mysql.VARCHAR(length=8), nullable=False),
        sa.Column("c_name", mysql.VARCHAR(length=100), nullable=False),
        sa.PrimaryKeyConstraint("c_id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
