"""Added new table

Revision ID: 7582ab4f5165
Revises: 00fdbe2e4fec
Create Date: 2024-02-17 17:45:07.943962

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7582ab4f5165"
down_revision = "00fdbe2e4fec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "choose_course",
        sa.Column("c_id", sa.String(length=6), nullable=False),
        sa.Column("t_id", sa.String(length=8), nullable=False),
        sa.Column("c_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("c_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("choose_course")
    # ### end Alembic commands ###
